### ISSUE TITLE
Serverside error when sorting (fails to sort)

### ISSUE THREAD

**Issue by ClassicsWoTWorkshop** [Chailotl/inventory-sort#3]
Minecraft version: 1.20.4
Fabric version: 0.15.7

Getting the following server-side error when attempting to use the mod on my server (the mod is installed both on client and server).
```
[11:02:38] [Server thread/ERROR]: Error executing task on Server
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "config" is null
        at com.chailotl.inventorysort.InventoryManager.sortInventory(InventoryManager.java:73) ~[inventory-sort-1.0.3+1.20.2.jar:?]
        at com.chailotl.inventorysort.InventorySort.lambda$onInitialize$0(InventorySort.java:26) ~[inventory-sort-1.0.3+1.20.2.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:797) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:779) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:773) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.redirect$cfo000$tick-stasis$waitUntilResumed(MinecraftServer.java:6919) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:687) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

I noticed no config file was present in the server configs folder, but placing one there makes no difference.

**Comment by Chailotl** [comment]
What mods do you have installed? In particular, any mods that also use owo-lib for their configs, as someone else had reported that mods with malformed owo-lib configs affect this mod.

The reason the error is server-side is because the client syncs its config to the server, which uses it to do the sorting for optimization reasons.

**Comment by ClassicsWoTWorkshop** [comment]
> What mods do you have installed? In particular, any mods that also use owo-lib for their configs, as someone else had reported that mods with malformed owo-lib configs affect this mod.
> 
> The reason the error is server-side is because the client syncs its config to the server, which uses it to do the sorting on a per-client's preferences basis for optimization reasons.

I am not using any other mods which rely on owo-lib currently (installed it purely to run this mod), but I do have quite a few other mods (read: ~60ish serverside).

**Comment by Chailotl** [comment]
I see, could you still list those mods for me, and to try the inventory sort mod in isolation?

**Comment by Chailotl** [comment]
Since no mod list was provided for me to be able to diagnose the issue I'm going to have to close this

**Comment by ClassicsWoTWorkshop** [comment]
> Since no mod list was provided for me to be able to diagnose the issue I'm going to have to close this

I apologize for the lack of response to your previous message; meant to compile the list but got busy with other matters. I also no longer have a copy of the exact modslist I used back when the issue was occurring. If I run into the issue again when using the mod in the future, I'll compile a list *before* creating an issue report. My apologies once again, and thank you for your time regardless.

**Comment by Chailotl** [comment]
It's alright, if you come across this issue again I'd be more than happy to fix it! As far as I can tell from having seen a similar issue with another mod of mine, it's an issue with owo-lib itself, which the dev has neglected to do anything about :/
